### ISSUE TITLE
Invoke contracts' payable method on asset Transfers

### ISSUE THREAD

**Issue by belane** [neo-project/proposals#108]
I would love that smart contracts could react to asset transfers, I'm not talking about the `Mint` function, but rather that a smart contract can react, execute, upon receiving NEO or any asset.
(remember our old friend `AplicationR` from `NEP7`?)

After studying several options we found that the solution is right in front of us.
In Native Contracts (NEO/GAS) we can add a call to the address in if the destination is a contract.

In the `Transfer` method of the native contracts we can include a check of whether the destination account is a contract address, check if it has the payable flag and if so, invoke a specific method of the contract, for example `bool Payable()`

`Payable` method can be included in the `NEP5` standard and must return `True` if everything is correct or throw an exception otherwise.

In this way smart contracts can react to payments without users having to build a special transaction, invoke `Mint` or whatever.
Therefore, Mint invocations won't need a second `APPCALL`, saving network and blockchain resources.

It also gives to the contract full management of received payments such as denying money receipts, issuing refunds, etc ...

**Comment by igormcoelho** [comment]
@erikzhang @shargon I think I found an interesting solution for this. Please correct me if I missed some recent development.

Suppose we don't make contracts pay for dynamic invoke during deployment, but we make users pay (or not) for it, during invocations (a tiny extra cost).

User wallets will likely disable this, unless they need it (as a failed dynamic invoke would cause FAULT if non paid).

Now, before invoking the "payable" method on other contract, we execute some Interop that requires Manifest/MethodList and verify that the remote contract *actually requires* some payable "reaction".

Ok, now its easy for wallets: if destination requires payable action, it enables dynamic invoke, otherwise it doesn't (and user saves gas).

In any case, this NEP will still be necessary for NEP5 to declare its "willigness" to call remote payable, but I think this resolves the "dynamic invoke dillema".

**Comment by erikzhang** [comment]
Maybe we can add a new SYSCALL: `Contract.CallIfExists()`. Or we can just add a new flag to `CallFlags`.

**Comment by igormcoelho** [comment]
Good idea @erikzhang , automatically checks manifest, simplify a lot coding.
Regarding users paying dynamic invoke fees per execution call, only if needed, instead of contract paying bigger amounts... do you see something like this reasonable? Good thing is that becomes easier to execute parallel tx, if dyn invoke fees are not required in that precise tx.

**Comment by erikzhang** [comment]
I'm sorry I think `CallIfExists` is not a good idea. When you call a contract, you might expect a return value. But if the method does not exist, then there is no return value. Maybe we can add a new SYSCALL `Contract.MethodExists()` to detect whether the method exists.

**Comment by igormcoelho** [comment]
Makes sense Erik, otherwise it would require some advanced C# "out" abstraction, to express meaning on smart contract. MethodExists is good enough.

**Comment by shargon** [comment]
> I'm sorry I think CallIfExists is not a good idea. When you call a contract, you might expect a return value. But if the method does not exist, then there is no return value. Maybe we can add a new SYSCALL Contract.MethodExists() to detect whether the method exists.

Maybe we can force this syscall if it has a empty return? for this case we need a `void`

**Comment by erikzhang** [comment]
> Maybe we can force this syscall if it has a empty return? for this case we need a void

But if this is the case, how do you tell whether the call was successful?

**Comment by shargon** [comment]
If it doesn't throw an exception. 
Maybe we can create a syscall for this, `EmitPayment`, generate the payment and if it doesn't exists push a value.

**Comment by roman-khimov** [comment]
I think system-induced invocations don't have any of these problems. `onPayment` doesn't exist? OK, moving on without invocation. `onPayment` returns an error? It will always be properly handled. `onPayment` throws an exception? We can guarantee that it'll be handled by aborting the execution.

**Comment by igormcoelho** [comment]
If I understood correctly @shargon , a MethodExists is better because its it never throws exception , always boolean. If the call throws,  it could be that it was an error in the method itself (but it exists). So you neeed to catch specific exception, like "methodNorFound", but what happens if your call tries to call other method that doesn't exist... will you know that payable method exists but it failed (so you must fail) or you think method doesn't exist and proceed besides the error (that will cause inconsistency on the contract expecting payable method execution)?
On the other hand, exception approach is good when we dont need to specify parametee lists for MethodExists... if it works, it doesn't throw, naturally.
