### ISSUE TITLE
NEP-51 (5.1), Token Standard Requiring Optional Methods

### ISSUE THREAD

**Issue by anfn101** [neo-project/proposals#59]
**Proposal**
----------------------------------------------------------
Name: NEP-51
Title: Token Standard Requiring Optional Methods
Author: afong@cityofzion.io
Status: Draft
Created: 21 July 2018
Resolution: https://github.com/neo-project/proposals/pull/58

Abstract
-----------------------------------------------------------
In the absence of NEP-5 reversion to Final state going through (issue #57), I propose NEP-51 (5.1), which requires the optional methods recently removed from the NEP-5 standard. 

See: https://github.com/neo-project/proposals/pull/58 for a draft of NEP-51, which is just the original NEP-5 with optional methods made required.

**Comment by mwherman2000** [comment]
@erikzhang I've created https://github.com/neo-project/proposals/pull/60 to be reviewed and approved.

@birmas @anfn101 @lllwvlvwlll

**Comment by birmas** [comment]
I don't understand why #60 has been submitted in favour of this issue.

Let's assume we all support nep10 to convey the functionality of our contract: This proposal would mean a single entry, in supported standards,  of Nep-51 whereas #60 would require nep5 and "nep-latest" to be declared.

It was suggested on discord that this nep would never be approved by the neo project admins because "that isn't the direction the community is heading" - I would like to see some details to back that statement if that is indeed that case

As someone about to deploy a nep5(1) contract to mainnet i completely support these additional methods.

**Comment by mwherman2000** [comment]
@birmas Re: [neo-project/proposals] NEP-51 (5.1), Token Standard Requiring Optional Methods (#59)
RE: I also have little faith in the opinion of someone who seems to be using their nep contribution status for their own personal gain: https://www.google.com.au/search?q=site%3Agithub.com+mwherman2000+bounty+-"neo-project"&oq=site%3Agithub.com+mwherman2000+bounty+-"neo-project"

Chris, you really need to grow up.  This was a bounty contest sponsored by the Alchemint to which I applied my knowledge and experience.

You're now officially a member of the Gang of Zion.
