### ISSUE TITLE
Proposal for UTXO Tokens

### ISSUE THREAD

**Issue by igormcoelho** [neo-project/proposals#88]
After global assets are abolished, some people may want to keep UTXO behavior on their tokens. Perhaps we can start creating a standard for that.

In my opinion, it could be nearly the same as NEP-5 (including a consolidated balance), but with minor differences on transfer function (including `unspent inputs` and multiple `outputs`).
That won't be very challenging to implement I think.

**Comment by erikzhang** [comment]
I think NEP-5 is just a token standard. It doesn't specify what way to store it behind, so you can also use UTXOs to store the user's account.

**Comment by saltyskip** [comment]
Good idea igor, @erikzhang I think standard is still necessary because native contract still need to expose something like inputs/outputs to developer. Of course there can be simple transfer function where contract itself manages the strategy for how to use UTXO's, but for advanced functionalities it is still likely that these UTXO type methods need to be exposed.

**Comment by roman-khimov** [comment]
UTXO is gone, maybe we close this now.
